ALTER TABLE TBL_MSGCODE ADD CONSTRAINT FKC875816D2812B8BE
FOREIGN KEY ( USER_ID ) REFERENCES TBL_USER ( ID ) ENABLECREATE TABLE TBL_MSGCODE (
ID NUMBER(10, 0) NOT NULL ,
SENDFLAG NUMBER(10, 0) NOT NULL ,
CREATETIME DATE ,
 STATUS NUMBER(10, 0) NOT NULL ,
 VALIDTIME DATE ,
 SENDTIME DATE ,
  CODE VARCHAR2(255 BYTE) ,
    MOBILE VARCHAR2(255 BYTE) ,
     CONSTRAINT SYS_C0053623 PRIMARY KEY ( ID )


create table sw_MSGCODE
(
 id int(11) primary key  auto_increment,
 SENDFLAG int(11) NOT NULL default 0,
CREATETIME timestamp NOT NULL default CURRENT_TIMESTAMP,
 STATUS int(11) NOT NULL default 0,
 VALIDTIME timestamp NOT NULL,
 SENDTIME timestamp NOT NULL default CURRENT_TIMESTAMP,
  CODE varchar(255) NOT NULL,
  MOBILE varchar(255) NOT NULL
);